### ISSUE TITLE
java.io.IOException: Cannot run program "python": error=2, No such file or directory

### ISSUE THREAD

**Issue by bohemia420** [sllynn/spark-xgboost#17]
I dont necessarily see this problem with Spark, more than what might be with `XGBoost4j` or its this python wrapper. 

I am(or have rather used all-) Spark 3.0.0 and following XGBoost jars:
- https://mvnrepository.com/artifact/ml.dmlc/xgboost4j-spark_2.12/1.0.0
- https://mvnrepository.com/artifact/ml.dmlc/xgboost4j_2.12/1.0.0

```
spark-3.0.0-bin-hadoop2.7$ ./bin/spark-submit --master local[*] --jars /home/sumit/Downloads/xgboost4j-spark_2.12-1.0.0.jar,/home/sumit/Downloads/xgboost4j_2.12-1.0.0.jar hello.py
```

yet, at `model = cv.fit(train_sdf_prepared)` I get the following error:
```
java.io.IOException: Cannot run program "python": error=2, No such file or directory
```

and for the full stacktrace:
```
java.io.IOException: Cannot run program "python": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at java.base/java.lang.Runtime.exec(Runtime.java:416)
	at java.base/java.lang.Runtime.exec(Runtime.java:313)
	at ml.dmlc.xgboost4j.java.RabitTracker.startTrackerProcess(RabitTracker.java:136)
	at ml.dmlc.xgboost4j.java.RabitTracker.start(RabitTracker.java:170)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.startTracker(XGBoost.scala:393)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:549)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:191)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:40)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:150)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 22 more
22/12/22 14:11:43 ERROR RabitTracker: FAULT: failed to start tracker process
22/12/22 14:11:43 ERROR XGBoostSpark: the job was aborted due to 
java.lang.IllegalArgumentException: requirement failed: FAULT: Failed to start tracker
	at scala.Predef$.require(Predef.scala:281)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.startTracker(XGBoost.scala:393)
	at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:549)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:191)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:40)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:150)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

for sure, the "python" problem is not of spark, because the following just work so well:
```
train_sdf_prepared.cache()
train_sdf_prepared.count()
```

despite having set 
PYSPARK_PYTHON, PYSPARK_DRIVER_PYTHON, and also explicit alias in `~/.bashrc` for pointing python to python3. 

WHAT COULD POSSIBLY BE TRIGGERING THIS PUNY ISSUE WANTING "PYTHON" TO BE FOUND?

**Comment by khanna-lqc** [comment]
hello, hacky but what worked for me was just a puny symlink `ls -s /usr/env/python3 /usr/env/python`- no PYSPARK_PYTHON etc like env vars to be set. 
Also, it works for all the JAR versions 1.0.0+. 

I am closing the issue, but however perhaps as another issue, it would be great to have SHAP supporting sparkxgb.xgboost.XGBoostClassifierModel

```
shap.utils._exceptions.InvalidModelError: Model type not yet supported by TreeExplainer: <class 'sparkxgb.xgboost.XGBoostClassificationModel'>
```
